-- PHONE NUMBER WITH 10 DIGITS AND NO ALPHABET RESTRICTION ON CUSTOMER TABLE
COMMIT;
CREATE OR REPLACE TRIGGER TRIG_PHONENO
BEFORE INSERT OR UPDATE ON CUSTOMER
FOR EACH ROW
BEGIN
    IF NOT REGEXP_LIKE(:NEW.CUST_PHONENO,'^[[:digit:]]{10}$') THEN
        RAISE_APPLICATION_ERROR(-20000,'YOU ENTERED INVALID PHONE NUMBER');
    END IF;
END;
/

-- TRIGGER FOR THOSE DAYS THAT SHOULD HAVE MINIMUM 7 DAYS OF CARAVAN BOOKED
COMMIT;
CREATE OR REPLACE TRIGGER TRIG_MINCARAVANBOOKING
BEFORE INSERT OR UPDATE ON BOOKING
FOR EACH ROW
DECLARE
v_newdate varchar(20);
BEGIN
    SELECT ABS (TO_DATE(:NEW.DATE_ARRIVAL, 'MM/DD/YYYY') - TO_DATE(:NEW.DATE_DEPARTURE, 'MM/DD/YYYY')) INTO v_newdate
    FROM DUAL;
        IF v_newdate<7 THEN
            RAISE_APPLICATION_ERROR(-20000,'THE CARAVAN SHOULD BE BOOKED FOR MINIMUM 7 DAYS!');
        END IF;
END;
/

-- TRIGGER FOT THE DAYS BETWEEN DAY OF BOOKING TO DAY OF ARRIVAL SHOULD BE OF 4 WEEKS
COMMIT;
CREATE OR REPLACE TRIGGER TRIG_MINWEEKSDEPOSIT
BEFORE INSERT OR UPDATE ON BOOKING
FOR EACH ROW
DECLARE 
v_weekdays varchar(20);
BEGIN
    SELECT ABS (TO_DATE(:NEW.BOOKING_DATE, 'MM/DD/YYYY') - TO_DATE(:NEW.DATE_ARRIVAL, 'MM/DD/YYYY')) INTO v_weekdays
    FROM DUAL;
        IF v_weekdays<28 OR v_weekdays>28 THEN
            RAISE_APPLICATION_ERROR(-20000,'THE INTERVAL OF WEEKS BETWEEN DEPOSIT AND ARRIVAL MUST BE OF 4 WEEKS!');
        END IF;
END;
/

-- TRIGGER FOR OWNER THAT THEY SHOULD ATLEAST BE OF AGE 18 TO OWN THE CARAVAN
COMMIT;
CREATE OR REPLACE TRIGGER TRIG_OWNERAGE
BEFORE INSERT OR UPDATE ON OWNER
FOR EACH ROW
BEGIN
    IF(:NEW.OWNER_AGE<18) THEN
        RAISE_APPLICATION_ERROR(-20501,'YOU HAVE NOT REACHED A LEGAL AGE TO OWN CARAVAN');
    END IF;
END;
/

--  TABLE LEVEL TRIGGER ON WEEKEND RESTRICTION TO ACESS STAFF TABLE
COMMIT;
CREATE OR REPLACE TRIGGER TRIG_STAFF
BEFORE INSERT OR UPDATE ON STAFF
DECLARE
dummy integer;
BEGIN 
    IF (TO_CHAR(SYSDATE,'DY')='SAT' OR TO_CHAR(SYSDATE,'DY')='SUN') THEN
        RAISE_APPLICATION_ERROR(-20501,'THE STAFF TABLE CAN NOT BE ACCESSED DURING WEEKENDS!');
    END IF;
END;
/